version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgsql
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "user=postgres dbname=todoapp sslmode=disable password=pgsql host=db port=5432"
    ports:
      - "8080:8080"
    command: [ "./app" ]  # Ensure this matches your built Go binary name

volumes:
  postgres_data:
