apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DATABASE_URL: "postgres://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.database }}?sslmode=disable"
