apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-to-do-app
  labels:
    app: {{ .Release.Name }}-to-do-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-to-do-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-to-do-app
    spec:
      containers:
        - name: to-do-app
          image: to-do-app
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources: {{ .Values.resources | toYaml  | nindent 12 }}

