apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-app
  labels:
    app: {{ .Release.Name }}-todo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-todo-app
    spec:
      containers:
      - name: {{ .Release.Name }}-todo-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "{{ .Release.Name }}-postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgres-secret
              key: password
