apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
data:
  username: {{ .Values.postgresql.user | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}
