replicaCount: 1

image:
  repository: my-todo-app-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

postgresql:
  image: postgres
  tag: 15
  user: postgres
  password: pgsql
  database: todoapp
  servicePort: 5432
  storageSize: 1Gi

ingress:
  enabled: false
  annotations: {}
  host: my-todo-app.local
